//
// Created by Daud Akhtar Naveed on 31/12/2017.
//

#ifndef PLAGIARISM_DETECTOR_RABINKARP_TEST_HPP
#define PLAGIARISM_DETECTOR_RABINKARP_TEST_HPP

void rabinkarp_test();

#endif //PLAGIARISM_DETECTOR_RABINKARP_TEST_HPP
